server:
  port: 8080

spring:
  application:
    name: panacea
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.200:3306/wf?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: "root"
    password: "AES@root"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
