
server:
  port: 8888

spring:
  application:
    name: zhuooo-asset
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.30:3306/wpy_qjt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: "root"
    password: "root"

mybatis:
  configuration:
    map-underscore-to-camel-case: true

